name: Build and Release Kernel
permissions:
  contents: write
  actions: write
on:
  workflow_dispatch:
    inputs:
      build-kernel:
        description: 'Build Kernel ?'
        required: true
        type: boolean
        default: true
      release-kernel:
        description: 'Release Kernel ?'
        required: true
        type: boolean
        default: true
jobs:
  build-kernel:
    name: "Step Build Kernel"
    uses: ./.github/workflows/build-kernel.yml
    secrets: inherit
    strategy:
      fail-fast: true
    if: github.event_name == 'workflow_dispatch' && inputs.build-kernel == true
  release-kernel:
    name: "Step Release Kernel"
    runs-on: ubuntu-latest
    needs:
      - build-kernel
    if: github.event_name == 'workflow_dispatch' && inputs.release-kernel == true
    env:
      REPO_OWNER: cat-mao-web
      REPO_NAME: NonGKI_Kernel_Build
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_NAME: "Pre-built"
      RELEASE_NOTES: |
        Below is the codename reference table. Please select the image or archive you need based on this table.
        | Device Name | Codename | Kernel | System | Android | Method | KernelSU | SuSFS | Re:Kernel | KPM | BBG | Hook |
        |----------|----------|----------|----------|----------|----------|----------|----------|----------|----------|----------|----------|
        | PEGM00 | PEGM00 | 4.9.157-perf+ | Based-AOSP | 13 | AnyKernel3 | SukiSU(U) | ✅ | ❌ | ✅ | ❌ | Inline |
        - Specific device information: [Supported List](sslocal://flow/file_open?url=Supported_list.md&flow_extra=eyJsaW5rX3R5cGUiOiJjb2RlX2ludGVycHJldGVyIn0=).
        - The KernelSU version is for reference only. It is normal for the KernelSU version embedded in SUSFS to be lower.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts
      - name: Generate and Create New Tag
        run: |
          LATEST_TAG=$(gh api repos/$REPO_OWNER/$REPO_NAME/tags --jq '.[0].name')
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="0000000001"
          fi
          NEW_TAG=$(date +%s)
          echo "New tag: $NEW_TAG"
          TIME=$(date +"%Y-%m-%d %H:%M")
          echo "TIME=$TIME" >> $GITHUB_ENV
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push --tags
          git clone -b master https://github.com/backslashxx/KernelSU.git KernelSU-Magic
          KSU_MAGIC_VERSION=$(cd KernelSU-Magic && expr $(/usr/bin/git rev-list --count HEAD) + 10200 - 32)
          git clone -b main https://github.com/rsuntk/KernelSU.git KernelSU-rsuntk
          KSU_RSUNTK_VERSION=$(cd KernelSU-rsuntk && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
          git clone -b builtin https://github.com/ShirkNeko/SukiSU-Ultra.git KernelSU-SukiSU-Ultra
          KSU_SUKISU_ULTRA_VERSION=$(cd KernelSU-SukiSU-Ultra && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
          git clone -b legacy https://github.com/KernelSU-Next/KernelSU-Next.git KernelSU-Next
          KSU_NEXT_VERSION=$(cd KernelSU-Next && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
          git clone -b main https://github.com/ReSukiSU/ReSukiSU.git KernelSU-ReSukiSU
          KSU_RESUKISU_VERSION=$(cd KernelSU-ReSukiSU && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "[KernelSU-Magic](sslocal://flow/file_open?url=https%3A%2F%2Fgithub.com%2Fbackslashxx%2FKernelSU&flow_extra=eyJsaW5rX3R5cGUiOiJjb2RlX2ludGVycHJldGVyIn0=) Version: $KSU_MAGIC_VERSION  " >> $GITHUB_ENV
          echo "[KernelSU-rsuntk](sslocal://flow/file_open?url=https%3A%2F%2Fgithub.com%2Frsuntk%2FKernelSU&flow_extra=eyJsaW5rX3R5cGUiOiJjb2RlX2ludGVycHJldGVyIn0=) Version: $KSU_RSUNTK_VERSION  " >> $GITHUB_ENV
          echo "[KernelSU-SukiSU-Ultra](sslocal://flow/file_open?url=https%3A%2F%2Fgithub.com%2FShirkNeko%2FSukiSU-Ultra&flow_extra=eyJsaW5rX3R5cGUiOiJjb2RlX2ludGVycHJldGVyIn0=) Version: $KSU_SUKISU_ULTRA_VERSION  " >> $GITHUB_ENV
          echo "[KernelSU-Next](sslocal://flow/file_open?url=https%3A%2F%2Fgithub.com%2FKernelSU-Next%2FKernelSU-Next&flow_extra=eyJsaW5rX3R5cGUiOiJjb2RlX2ludGVycHJldGVyIn0=) Version: $KSU_NEXT_VERSION  " >> $GITHUB_ENV
          echo "[KernelSU-ReSukiSU](sslocal://flow/file_open?url=https%3A%2F%2Fgithub.com%2FReSukiSU%2FReSukiSU&flow_extra=eyJsaW5rX3R5cGUiOiJjb2RlX2ludGVycHJldGVyIn0=) Version: $KSU_RESUKISU_VERSION  " >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          prerelease: false
          release_name: "${{ env.RELEASE_NAME }} ${{ env.TIME }}"
          body: ${{ env.RELEASE_NOTES }}
      - name: Upload Release Assets Dynamically
        run: |
          for file in ./downloaded-artifacts/Kernel-*/*; do
              if [ -d "$file" ]; then
                  continue
              fi
              echo "Uploading $file..."
              gh release upload ${{ env.NEW_TAG }} "$file"
          done
      - name: Display Files Uploaded
        run: |
          echo "GitHub release created with the following files:"
          ls ./downloaded-artifacts/**/*
